spring:
  application:
    name: discovery-server
  profiles:
    active: dev,local
server:
  port: 8761 #default port where discovery client is registered

eureka:
  client:
    eurekaServerConnectTimeoutSeconds: 5
    enabled: true
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0